export interface PharmacyProduct {
  id: string;
  image: string;
  name: string;
  strainType: string;
  manufacturer: string;
  genetics: string;
  growingMethod: string;
  servingType: string;
  thc: number;
  cbd: number;
  cbg?: number;
  cbn?: number;
  terpenes: {
    name: string;
    percentage: number;
  }[];
  batchNumber: string;
  productionDate: string;
  expiryDate: string;
  packPrice: number;
  packGrams: number;
  wholesalePrice?: number;
  wholesaleMinUnits?: number;
  inStock: boolean;
  gmpCertified: boolean;
  badge?: 'new' | 'sale';
}

export const pharmacyProducts: PharmacyProduct[] = [
  {
    id: 'alaska-a5',
    image: '/products/prod1.png',
    name: 'Alaska A5',
    strainType: 'אינדיקה דומיננטי',
    manufacturer: 'IMC פארמה',
    genetics: 'Northern Lights x Haze',
    growingMethod: 'אורגני מקורה',
    servingType: 'תפרחת',
    thc: 22,
    cbd: 1,
    cbg: 0.8,
    cbn: 0.3,
    terpenes: [
      { name: 'Myrcene', percentage: 1.2 },
      { name: 'Caryophyllene', percentage: 0.8 },
      { name: 'Limonene', percentage: 0.5 },
    ],
    batchNumber: 'AL-2024-1287',
    productionDate: '15/11/2024',
    expiryDate: '15/11/2025',
    packPrice: 299,
    packGrams: 10,
    wholesalePrice: 265,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
    badge: 'sale',
  },
  {
    id: 'blue-dream-b3',
    image: '/products/prod2.png',
    name: 'Blue Dream B3',
    strainType: 'סאטיבה דומיננטי',
    manufacturer: 'Tikun Olam',
    genetics: 'Blueberry x Haze',
    growingMethod: 'הידרופוני',
    servingType: 'שמן',
    thc: 18,
    cbd: 2,
    cbg: 0.5,
    cbn: 0.2,
    terpenes: [
      { name: 'Pinene', percentage: 1.0 },
      { name: 'Myrcene', percentage: 0.7 },
      { name: 'Caryophyllene', percentage: 0.4 },
    ],
    batchNumber: 'BD-2024-0892',
    productionDate: '20/11/2024',
    expiryDate: '20/11/2025',
    packPrice: 280,
    packGrams: 10,
    wholesalePrice: 245,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
    badge: 'new',
  },
  {
    id: 'og-kush-k1',
    image: '/products/prod3.png',
    name: 'OG Kush K1',
    strainType: 'היברידי',
    manufacturer: 'Cannbit',
    genetics: 'Chemdawg x Hindu Kush',
    growingMethod: 'אורגני מקורה',
    servingType: 'תפרחת',
    thc: 24,
    cbd: 0.5,
    cbg: 1.0,
    cbn: 0.4,
    terpenes: [
      { name: 'Limonene', percentage: 1.5 },
      { name: 'Myrcene', percentage: 0.9 },
      { name: 'Linalool', percentage: 0.3 },
    ],
    batchNumber: 'OG-2024-0456',
    productionDate: '10/11/2024',
    expiryDate: '10/11/2025',
    packPrice: 320,
    packGrams: 10,
    wholesalePrice: 285,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'eran-almog',
    image: '/products/prod4.jpg',
    name: 'Eran Almog',
    strainType: 'אינדיקה דומיננטי',
    manufacturer: 'Tikun Olam',
    genetics: 'Proprietary Indica',
    growingMethod: 'אורגני מקורה',
    servingType: 'תפרחת',
    thc: 28,
    cbd: 0.3,
    cbg: 0.6,
    cbn: 0.5,
    terpenes: [
      { name: 'Myrcene', percentage: 1.8 },
      { name: 'Caryophyllene', percentage: 1.1 },
      { name: 'Humulene', percentage: 0.4 },
    ],
    batchNumber: 'EA-2024-0721',
    productionDate: '05/12/2024',
    expiryDate: '05/12/2025',
    packPrice: 350,
    packGrams: 10,
    wholesalePrice: 310,
    wholesaleMinUnits: 10,
    inStock: false,
    gmpCertified: true,
  },
  {
    id: 'avidekel-cbd',
    image: '/products/prod1.png',
    name: 'Avidekel CBD',
    strainType: 'CBD דומיננטי',
    manufacturer: 'Tikun Olam',
    genetics: 'Proprietary CBD',
    growingMethod: 'אורגני מקורה',
    servingType: 'שמן',
    thc: 1,
    cbd: 16,
    cbg: 0.4,
    cbn: 0.1,
    terpenes: [
      { name: 'Myrcene', percentage: 0.6 },
      { name: 'Pinene', percentage: 0.5 },
      { name: 'Linalool', percentage: 0.8 },
    ],
    batchNumber: 'AV-2024-0334',
    productionDate: '01/12/2024',
    expiryDate: '01/12/2025',
    packPrice: 340,
    packGrams: 30,
    wholesalePrice: 300,
    wholesaleMinUnits: 5,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'midnight-m2',
    image: '/products/prod2.png',
    name: 'Midnight M2',
    strainType: 'היברידי',
    manufacturer: 'IMC פארמה',
    genetics: 'White Widow x Amnesia',
    growingMethod: 'הידרופוני',
    servingType: 'תפרחת',
    thc: 20,
    cbd: 3,
    cbg: 0.7,
    cbn: 0.3,
    terpenes: [
      { name: 'Caryophyllene', percentage: 1.3 },
      { name: 'Limonene', percentage: 0.9 },
      { name: 'Myrcene', percentage: 0.6 },
    ],
    batchNumber: 'MN-2024-0567',
    productionDate: '18/11/2024',
    expiryDate: '18/11/2025',
    packPrice: 290,
    packGrams: 10,
    wholesalePrice: 255,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'paris-og-p1',
    image: '/products/prod3.png',
    name: 'Paris OG P1',
    strainType: 'אינדיקה דומיננטי',
    manufacturer: 'Cannbit',
    genetics: 'Headband x Lemon OG',
    growingMethod: 'אורגני מקורה',
    servingType: 'תפרחת',
    thc: 26,
    cbd: 0.8,
    cbg: 0.9,
    cbn: 0.4,
    terpenes: [
      { name: 'Limonene', percentage: 1.4 },
      { name: 'Myrcene', percentage: 1.0 },
      { name: 'Caryophyllene', percentage: 0.7 },
    ],
    batchNumber: 'PO-2024-0891',
    productionDate: '12/12/2024',
    expiryDate: '12/12/2025',
    packPrice: 330,
    packGrams: 10,
    wholesalePrice: 290,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'green-crack-g1',
    image: '/products/prod4.jpg',
    name: 'Green Crack G1',
    strainType: 'סאטיבה דומיננטי',
    manufacturer: 'Seach',
    genetics: 'Skunk #1 x Afghani',
    growingMethod: 'הידרופוני',
    servingType: 'תפרחת',
    thc: 21,
    cbd: 0.5,
    cbg: 0.6,
    cbn: 0.2,
    terpenes: [
      { name: 'Pinene', percentage: 1.2 },
      { name: 'Limonene', percentage: 1.1 },
      { name: 'Myrcene', percentage: 0.4 },
    ],
    batchNumber: 'GC-2024-0223',
    productionDate: '08/12/2024',
    expiryDate: '08/12/2025',
    packPrice: 275,
    packGrams: 10,
    wholesalePrice: 240,
    wholesaleMinUnits: 10,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'dorit-d3',
    image: '/products/prod1.png',
    name: 'Dorit D3',
    strainType: 'היברידי',
    manufacturer: 'Bazelet',
    genetics: 'Girl Scout Cookies x OG Kush',
    growingMethod: 'אורגני מקורה',
    servingType: 'שמן',
    thc: 19,
    cbd: 4,
    cbg: 0.8,
    cbn: 0.3,
    terpenes: [
      { name: 'Caryophyllene', percentage: 1.1 },
      { name: 'Limonene', percentage: 0.8 },
      { name: 'Humulene', percentage: 0.5 },
    ],
    batchNumber: 'DR-2024-0445',
    productionDate: '22/11/2024',
    expiryDate: '22/11/2025',
    packPrice: 310,
    packGrams: 30,
    wholesalePrice: 275,
    wholesaleMinUnits: 5,
    inStock: true,
    gmpCertified: true,
  },
  {
    id: 'lemon-haze-l2',
    image: '/products/prod2.png',
    name: 'Lemon Haze L2',
    strainType: 'סאטיבה דומיננטי',
    manufacturer: 'Better',
    genetics: 'Silver Haze x Lemon Skunk',
    growingMethod: 'הידרופוני',
    servingType: 'תפרחת',
    thc: 23,
    cbd: 0.4,
    cbg: 0.5,
    cbn: 0.2,
    terpenes: [
      { name: 'Limonene', percentage: 1.8 },
      { name: 'Terpinolene', percentage: 0.9 },
      { name: 'Pinene', percentage: 0.6 },
    ],
    batchNumber: 'LH-2024-0678',
    productionDate: '25/11/2024',
    expiryDate: '25/11/2025',
    packPrice: 295,
    packGrams: 10,
    wholesalePrice: 260,
    wholesaleMinUnits: 10,
    inStock: false,
    gmpCertified: true,
  },
];
